Repository theforeman/foreman_openscap, pull requests merged in 2018-05, with the labels that each got.

#335 Fixes #23544 - Edit multiple host's OpenSCAP Proxy
  app/controllers/concerns/foreman_openscap/hosts_controller_extensions.rb
  app/helpers/concerns/foreman_openscap/hosts_helper_extensions.rb
  app/views/hosts/select_multiple_openscap_proxy.html.erb
  config/routes.rb
  lib/foreman_openscap/engine.rb
Labels: Needs testing, Not yet reviewed

#336 Correct the website URL in the gemspec
  foreman_openscap.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#334 Fixes #23259 - Fix resource switcher for breadcrumbs
  app/helpers/arf_reports_helper.rb
  app/views/arf_reports/show.html.erb
  app/views/arf_reports/show_html.html.erb
  app/views/policies/edit.html.erb
  app/views/scap_contents/edit.html.erb
  app/views/tailoring_files/edit.html.erb
  config/routes.rb
Labels: Needs testing, Waiting on contributor
