Repository theforeman/foreman_openscap, pull requests merged in 2019-04, with the labels that each got.

#373 Fixes #26510 - Make plugin work without ansible
  app/helpers/foreman_openscap_helper.rb
  app/helpers/policies_helper.rb
Labels: Needs testing

#374 Fixes #26523 - remove unneeded form_to_submit_id method
  app/helpers/policies_helper.rb
Labels: Ready to merge

#372 Fixes #26500 - Prevent model search in breadcrumbs
  app/helpers/policies_helper.rb
Labels: Needs testing, Not yet reviewed

#381 Fixes #26693 - Switch Result and Severity in Report
  app/views/arf_reports/_output.html.erb
Labels: Needs testing, Not yet reviewed

#382 Regenerate .rubocop_todo.yml
  .rubocop_todo.yml
Labels: Needs testing, Not yet reviewed, Waiting on contributor
