Repository theforeman/foreman_openscap, pull requests merged in 2019-05, with the labels that each got.

#378 Fixes #15493 - Fix scap content delete confirm message
  app/views/scap_contents/_list.html.erb
Labels: Ready to merge

#380 Fixes #26667 - Add pagination to policy dashboard
  app/assets/stylesheets/foreman_openscap/policy_dashboard.css
  app/controllers/policy_dashboard_controller.rb
  app/views/policy_dashboard/_policy_reports.html.erb
Labels: Ready to merge

#383 Fixes #26768 - Clicking Policy name should go on Edit page
  app/views/policies/_list.html.erb
Labels: Needs re-review, Needs testing

#379 Fixes #26662 - Fix adding deploy_by on mysql
  db/migrate/20190103093409_add_deployment_option_to_policy.foreman_openscap.rb
Labels: Ready to merge

#385 Fixes #26773 - include tailoring file profile
  app/controllers/policies_controller.rb
Labels: Needs testing, Not yet reviewed

#375 Fixes #26324 - Add API for policies ENC
  app/controllers/concerns/foreman_openscap/api/v2/hosts_controller_extensions.rb
  app/models/concerns/foreman_openscap/host_extensions.rb
  app/views/api/v2/hosts/policies_enc.json.rabl
  app/views/api/v2/hosts/policy_enc.json.rabl
  config/routes.rb
  lib/foreman_openscap/engine.rb
  test/functional/api/v2/hosts_controller_test.rb
Labels: Ready to merge

#377 Fixes #24608 - Policy dashboard shows unassigned hosts
  .rubocop_todo.yml
  app/helpers/policy_dashboard_helper.rb
  app/mailers/foreman_openscap/policy_mailer.rb
  app/models/concerns/foreman_openscap/host_extensions.rb
  app/services/foreman_openscap/policy_dashboard/data.rb
  app/views/policy_dashboard/_policy_reports.html.erb
  app/views/policy_dashboard/_policy_status_widget.html.erb
  test/test_plugin_helper.rb
  test/unit/concerns/host_extensions_test.rb
Labels: Ready to merge

#386 Fixes #18998 - UX improvements
  app/controllers/policies_controller.rb
  app/controllers/scap_contents_controller.rb
  app/controllers/tailoring_files_controller.rb
  app/models/foreman_openscap/policy.rb
  app/models/foreman_openscap/scap_content.rb
  app/models/foreman_openscap/tailoring_file.rb
  app/views/arf_reports/show.html.erb
  app/views/policies/_list.html.erb
  app/views/policies/index.html.erb
  app/views/scap_contents/_list.html.erb
  app/views/scap_contents/index.html.erb
  app/views/tailoring_files/_list.html.erb
  app/views/tailoring_files/index.html.erb
Labels: Needs re-review, Needs testing

#376 Fixes #26604 - Fix layout on policy dashboard
  app/assets/javascripts/foreman_openscap/policy_dashboard.js
  app/views/policy_dashboard/index.html.erb
  lib/foreman_openscap/engine.rb
Labels: 1.0, Ready to merge

#388 Fixes #26778 - Compliance report default action wrong
  app/views/arf_reports/_list.html.erb
Labels: Needs testing, Not yet reviewed

#387 Fixes #26001 - Search for Arf reports by partial policy name
  app/models/concerns/foreman_openscap/compliance_status_scoped_search.rb
Labels: Needs testing, Not yet reviewed

#389 Refs #26604 - Don't use ES6 syntax in assets pipeline
  app/assets/javascripts/foreman_openscap/policy_dashboard.js
Labels: Needs testing, Not yet reviewed

#391 Fixes #26884 - use dynamic attrs for Factory Bot 5.x compat
  test/factories/arf_report_factory.rb
  test/factories/asset_factory.rb
  test/factories/compliance_host_factory.rb
  test/factories/compliance_log_factory.rb
  test/factories/policy_arf_report_factory.rb
  test/factories/policy_factory.rb
  test/factories/scap_content_related.rb
Labels: Needs testing

#392 Fixes #26883 - use scoped_search 4.x syntax
  app/models/foreman_openscap/policy.rb
Labels: Needs testing, Not yet reviewed
