Repository theforeman/foreman_openscap, pull requests merged in 2020-12, with the labels that each got.

#460 Fixes #31423 - Update port param type
  db/migrate/20201202110213_update_puppet_port_param_type.rb
Labels: Needs testing

#461 Fix rubocop
  .rubocop.yml
  .rubocop_todo.yml
Labels: Needs testing, Waiting on contributor

#465 Fixes #31475 - bulk_upload API endpoint not working.
  app/controllers/api/v2/compliance/scap_contents_controller.rb
Labels: Needs testing, Not yet reviewed
