Repository theforeman/foreman_openscap, pull requests merged in 2020-11, with the labels that each got.

#453 Fixes #31186 - Removed method name collision with katello
  app/models/concerns/foreman_openscap/hostgroup_extensions.rb
  app/models/concerns/foreman_openscap/openscap_proxy_core_extensions.rb
Labels: Needs testing

#455 Fixes #31186 - Removed method name collision with katello
  app/models/concerns/foreman_openscap/hostgroup_extensions.rb
  app/models/concerns/foreman_openscap/openscap_proxy_core_extensions.rb
Labels: Needs testing, Not yet reviewed

#454 Fixes #31230 - Do not use digest in messages
  app/models/foreman_openscap/arf_report.rb
  test/factories/compliance_log_factory.rb
  test/functional/api/v2/compliance/arf_reports_controller_test.rb
Labels: Ready to merge

#452 Fixes #31008 - add status_link method to compliance-status
  app/models/foreman_openscap/compliance_status.rb
Labels: Ready to merge

#459 Fixes #31381 - Register REX features in to_prepare block
  lib/foreman_openscap/engine.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
