Repository theforeman/foreman_openscap, pull requests merged in 2020-07, with the labels that each got.

#440 Fix tests
  test/test_plugin_helper.rb
Labels: Needs testing, Waiting on contributor

#439 Fixes #30353 - Fix report uploads
  app/controllers/api/v2/compliance/arf_reports_controller.rb
  lib/foreman_openscap/helper.rb
Labels: Needs testing

#441 Fixes #30358 - Delete assets when unassigning hosts
  app/models/foreman_openscap/policy.rb
  test/unit/policy_test.rb
Labels: Needs testing

#442 Fixes #30353 - Fix report uploads
  app/controllers/api/v2/compliance/arf_reports_controller.rb
  lib/foreman_openscap/helper.rb
Labels: Needs testing, Not yet reviewed

#443 Fixes #30353 - Fix report uploads
  app/controllers/api/v2/compliance/arf_reports_controller.rb
  lib/foreman_openscap/helper.rb
Labels: Needs testing, Not yet reviewed

#444 Fixes #30404 - Add DSL docs for OpenSCAP plugin
  app/models/concerns/foreman_openscap/host_extensions.rb
Labels: Needs testing, Not yet reviewed
