Repository theforeman/foreman_openscap, pull requests merged in 2020-02, with the labels that each got.

#433 Fixes #29009 - Remove check for compliance status
  lib/foreman_openscap/engine.rb
Labels: Needs testing

#431 Fixes #28523 - Add profiles api
  app/controllers/api/v2/compliance/scap_content_profiles_controller.rb
  app/models/foreman_openscap/scap_content_profile.rb
  app/views/api/v2/compliance/scap_content_profiles/base.json.rabl
  app/views/api/v2/compliance/scap_content_profiles/index.json.rabl
  app/views/api/v2/compliance/scap_content_profiles/main.json.rabl
  config/routes.rb
  lib/foreman_openscap/engine.rb
  test/functional/api/v2/compliance/scap_content_profiles_controller_test.rb
Labels: Needs testing

#434 Fixes #29046 - Add title to arf report welcome page
  app/views/arf_reports/welcome.html.erb
Labels: Needs testing, Not yet reviewed

#429 Fixes #28481 - Make scap proxy port an int in enc
  app/models/concerns/foreman_openscap/smart_proxy_extensions.rb
  app/services/foreman_openscap/lookup_key_overrider.rb
  db/migrate/20200117135424_migrate_port_overrides_to_int.rb
Labels: Needs testing

#432 Fixes #28982 - Add description to plugin roles
  lib/foreman_openscap/engine.rb
Labels: Needs re-review, Needs testing
