Repository theforeman/foreman_openscap, pull requests merged in 2021-01, with the labels that each got.

#462 Fixes #31423 - Update port param type
  db/migrate/20201202110213_update_puppet_port_param_type.rb
Labels: Needs testing, Not yet reviewed

#466 Fixes #27378 - make deploy options clickable
  app/assets/stylesheets/foreman_openscap/policy.css
  app/helpers/.policies_helper.rb.swp
  app/helpers/policies_helper.rb
Labels: Needs re-review, Needs testing

#463 Fixes #27748 - Drop taxonomy_enabled checks
  app/models/foreman_openscap/arf_report.rb
  app/models/foreman_openscap/policy.rb
  db/seeds.d/75-job_templates.rb
  lib/foreman_openscap/bulk_upload.rb
Labels: Ready to merge

#464 Fixes #31458 - Correct breadcrumb layout
  app/helpers/arf_reports_helper.rb
  app/helpers/policies_helper.rb
  app/views/arf_reports/show.html.erb
  app/views/arf_reports/show_html.html.erb
  app/views/compliance_hosts/show.html.erb
  app/views/policies/edit.html.erb
  app/views/policies/show.html.erb
  app/views/scap_contents/edit.html.erb
  app/views/tailoring_files/edit.html.erb
Labels: Needs testing, Not yet reviewed
