Repository theforeman/foreman_openscap, pull requests merged in 2021-05, with the labels that each got.

#475 Fixes #32469 - Mark strings in _deployment_options_form as translatable
  app/views/policies/steps/_deployment_options_form.html.erb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#473 Switch to gh actions for tests
  .github/workflows/ruby_tests.yml
  lib/tasks/foreman_openscap_tasks.rake
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#474 Fixes #32463 Add OVAL Contents page
  .github/workflows/js_tests.yml
  .github/workflows/ruby_tests.yml
  app/graphql/types/oval_content.rb
  config/routes.rb
  jest.config.js
  lib/foreman_openscap/engine.rb
  package.json
  test/graphql/queries/oval_contents_query_test.rb
  webpack/components/EmptyState.js
  webpack/components/IndexLayout.js
  webpack/components/IndexLayout.scss
  webpack/components/IndexTable/IndexTableHelper.js
  webpack/components/IndexTable/index.js
  webpack/components/RuleSeverity/__snapshots__/RuleSeverity.test.js.snap
  webpack/components/withLoading.js
  webpack/global_index.js
  webpack/graphql/queries/ovalContents.gql
  webpack/helpers/pageParamsHelper.js
  webpack/helpers/pathsHelper.js
  webpack/routes/OvalContents/OvalContentsIndex/OvalContentsIndex.js
  webpack/routes/OvalContents/OvalContentsIndex/OvalContentsTable.js
  webpack/routes/OvalContents/OvalContentsIndex/__tests__/OvalContentsIndex.fixtures.js
  webpack/routes/OvalContents/OvalContentsIndex/__tests__/OvalContentsIndex.test.js
  webpack/routes/OvalContents/OvalContentsIndex/index.js
  webpack/routes/routes.js
  webpack/testHelper.js
Labels: Needs testing, Not yet reviewed

#478 Fixes #32573 - Add OVAL Policy show page
  app/graphql/types/cve.rb
  app/graphql/types/oval_policy.rb
  app/models/concerns/foreman_openscap/oval_facet_host_extensions.rb
  app/models/foreman_openscap/cve.rb
  app/models/foreman_openscap/host_cve.rb
  app/models/foreman_openscap/oval_policy.rb
  app/services/foreman_openscap/oval/cves.rb
  db/migrate/20210409095625_add_oval_policy_reference_to_cve.rb
  lib/foreman_openscap/engine.rb
  test/fixtures/cve_fixtures.rb
  test/unit/services/oval/cves_test.rb
  webpack/components/IndexTable/index.js
  webpack/components/withLoading.js
  webpack/graphql/queries/cves.gql
  webpack/graphql/queries/ovalPolicy.gql
  webpack/helpers/commonHelper.js
  webpack/helpers/globalIdHelper.js
  webpack/helpers/pathsHelper.js
  webpack/helpers/tableHelper.js
  webpack/routes/OvalContents/OvalContentsIndex/OvalContentsIndex.js
  webpack/routes/OvalContents/OvalContentsIndex/__tests__/OvalContentsIndex.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/OvalPoliciesIndex.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/OvalPoliciesTable.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/__tests__/OvalPoliciesIndex.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/__tests__/OvalPoliciesIndex.test.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/CvesTab.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/CvesTable.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/OvalPoliciesShow.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/OvalPoliciesShowHelper.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesShow.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesShow.test.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/index.js
  webpack/routes/routes.js
  webpack/testHelper.js
Labels: Needs testing

#479 Fixes #32579 - Add OVAL scan template and rex feature
  app/models/foreman_openscap/oval_policy.rb
  app/views/job_templates/run_oval_scans.erb
  lib/foreman_openscap/engine.rb
  test/functional/api/v2/compliance/oval_policies_controller_test.rb
  test/graphql/queries/oval_policies_query_test.rb
  test/unit/oval_policy_test.rb
  test/unit/oval_status_test.rb
Labels: Needs testing

#480 Fixes #32587 - Scan all hostgroups for OVAL policy
  app/graphql/types/oval_policy.rb
  lib/foreman_openscap/engine.rb
  webpack/graphql/queries/ovalPolicy.gql
  webpack/helpers/pathsHelper.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/OvalPoliciesShow.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/OvalPoliciesShowHelper.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesShow.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesShow.test.js
Labels: Needs testing
