Repository theforeman/foreman_openscap, pull requests merged in 2021-11, with the labels that each got.

#504 Fixes #33363 - Check permissions for OVAL policy edit
  webpack/components/EditableInput.js
  webpack/graphql/queries/ovalPolicy.gql
  webpack/routes/OvalPolicies/OvalPoliciesShow/DetailsTab.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesEdit.test.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesShow.fixtures.js
  webpack/testHelper.js
Labels: Needs testing

#483 Fixes #32719 - Add new OVAL policy page
  app/graphql/mutations/oval_policies/create.rb
  app/models/concerns/foreman_openscap/oval_facet_hostgroup_extensions.rb
  app/services/foreman_openscap/oval/configure.rb
  app/services/foreman_openscap/oval/setup_check.rb
  lib/foreman_openscap/engine.rb
  webpack/components/IndexTable/index.js
  webpack/components/LinkButton.js
  webpack/components/withLoading.js
  webpack/graphql/mutations/createOvalPolicy.gql
  webpack/helpers/formFieldsHelper.js
  webpack/helpers/globalIdHelper.js
  webpack/helpers/pathsHelper.js
  webpack/helpers/toastsHelper.js
  webpack/routes/OvalContents/OvalContentsIndex/__tests__/OvalContentsIndex.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/OvalPoliciesTable.js
  webpack/routes/OvalPolicies/OvalPoliciesNew/HostgroupSelect.js
  webpack/routes/OvalPolicies/OvalPoliciesNew/NewOvalPolicyForm.js
  webpack/routes/OvalPolicies/OvalPoliciesNew/NewOvalPolicyFormHelpers.js
  webpack/routes/OvalPolicies/OvalPoliciesNew/OvalPoliciesNew.js
  webpack/routes/OvalPolicies/OvalPoliciesNew/__tests__/OvalPoliciesNew.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesNew/__tests__/OvalPoliciesNew.test.js
  webpack/routes/OvalPolicies/OvalPoliciesNew/index.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/CvesTable.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/OvalPoliciesShowHelper.js
  webpack/routes/routes.js
  webpack/testHelper.js
Labels: Needs testing

#511 Fixes #33900 - Use compact tables in OVAL UI
  webpack/components/IndexTable/index.js
Labels: Needs testing

#512 Fixes #33755 - Do not show errors on inline edit reopen
  webpack/components/EditableInput.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesEdit.test.js
Labels: Needs testing

#516 Fix tests
  app/models/concerns/foreman_openscap/data_stream_content.rb
  app/models/foreman_openscap/oval_content.rb
  lib/foreman_openscap/engine.rb
Labels: Needs testing, Waiting on contributor

#515 Refs #33983 - Remove deprecated method call
  app/models/foreman_openscap/arf_report.rb
Labels: Needs testing, Needs re-review

#518 Fixes #33972 - Fix tailoring file selection
  app/helpers/policies_helper.rb
Labels: Needs testing, Not yet reviewed
