Repository theforeman/foreman_openscap, pull requests merged in 2021-08, with the labels that each got.

#467 Fixes #30970 - Replace mount_react_component helper with react_component
  app/helpers/arf_report_dashboard_helper.rb
  app/helpers/compliance_hosts_helper.rb
  app/views/arf_reports/_metrics.html.erb
  app/views/compliance_hosts/show.html.erb
  app/views/dashboard/_compliance_reports_breakdown_widget.html.erb
  app/views/policy_dashboard/_policy_chart_widget.html.erb
  test/helpers/arf_report_dashboard_helper_test.rb
  test/helpers/policy_dashboard_helper_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#481 Fixes #32646 - Move hostgroup descendants field to core
  lib/foreman_openscap/engine.rb
Labels: Needs testing, Not yet reviewed

#493 Fixes #33126 - Show proper 'permission denied' page
  webpack/components/EmptyState.js
  webpack/components/withLoading.js
  webpack/graphql/queries/currentUserAttributes.gql
  webpack/graphql/queries/cves.gql
  webpack/graphql/queries/ovalContents.gql
  webpack/graphql/queries/ovalPolicies.gql
  webpack/graphql/queries/ovalPolicy.gql
  webpack/helpers/permissionsHelper.js
  webpack/routes/OvalContents/OvalContentsIndex/OvalContentsIndex.js
  webpack/routes/OvalContents/OvalContentsIndex/__tests__/OvalContentsIndex.fixtures.js
  webpack/routes/OvalContents/OvalContentsIndex/__tests__/OvalContentsIndex.test.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/OvalPoliciesIndex.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/__tests__/OvalPoliciesIndex.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesIndex/__tests__/OvalPoliciesIndex.test.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/CvesTab.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesShow.fixtures.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/__tests__/OvalPoliciesShow.test.js
  webpack/routes/OvalPolicies/OvalPoliciesShow/index.js
  webpack/testHelper.js
Labels: Needs testing, Not yet reviewed

#496 Fixes #33194 - Show more columns for OVAL content
  webpack/routes/OvalContents/OvalContentsIndex/OvalContentsTable.js
  webpack/routes/OvalContents/OvalContentsIndex/__tests__/OvalContentsIndex.test.js
Labels: Needs testing, Not yet reviewed

#494 Fixes #33137 - Align with puppet moving to a plugin
  .github/workflows/ruby_tests.yml
  app/helpers/policies_helper.rb
  app/services/foreman_openscap/client_config/base.rb
  app/services/foreman_openscap/client_config/puppet.rb
  db/migrate/20200117135424_migrate_port_overrides_to_int.rb
  db/migrate/20201202110213_update_puppet_port_param_type.rb
  test/functional/api/v2/compliance/oval_reports_controller_test.rb
  test/test_plugin_helper.rb
  test/unit/policy_test.rb
  test/unit/services/hostgroup_overrider_test.rb
  test/unit/services/lookup_key_overrider_test.rb
Labels: Needs testing

#497 Fixes #28609 - Remove fix for skipping lone taxonomies assignment
  app/controllers/api/v2/compliance/arf_reports_controller.rb
Labels: Needs testing, Not yet reviewed

#500 Refs #33137 - tests work without Puppet plugin
  test/functional/api/v2/compliance/policies_controller_test.rb
  test/test_plugin_helper.rb
  test/unit/policy_test.rb
  test/unit/services/config_name_service_test.rb
  test/unit/services/hostgroup_overrider_test.rb
  test/unit/services/lookup_key_overrider_test.rb
Labels: Needs testing, Not yet reviewed
